# Generated by Django 3.1.4 on 2021-09-30 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_article_reporter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Reporter',
        ),
    ]
