# Generated by Django 3.1.4 on 2021-09-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_campus_institue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institue',
            old_name='under_campus',
            new_name='campus',
        ),
    ]
