# Generated by Django 3.1.4 on 2021-09-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_auto_20210930_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='campus_name',
            new_name='camp',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='institute_cnt',
            new_name='inst_cnt',
        ),
        migrations.RenameField(
            model_name='institue',
            old_name='institute_name',
            new_name='inst',
        ),
        migrations.RenameField(
            model_name='institue',
            old_name='campus',
            new_name='under_camp',
        ),
    ]
