# Generated by Django 3.1.4 on 2021-09-30 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_auto_20210930_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnderGraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_students', models.IntegerField(default=0)),
                ('total_no_of_final_year_students', models.IntegerField(default=0)),
                ('total_no_of_students_opt_higher_study_and_pay_crt', models.IntegerField(default=0)),
                ('under_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.institue')),
            ],
        ),
        migrations.CreateModel(
            name='PostGraduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_no_of_students', models.IntegerField(default=0)),
                ('total_no_of_final_year_students', models.IntegerField(default=0)),
                ('total_no_of_students_opt_higher_study_and_pay_crt', models.IntegerField(default=0)),
                ('under_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example.institue')),
            ],
        ),
    ]
