# Generated by Django 3.1.4 on 2021-10-10 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0010_postgraduates_undergraduates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='camp',
            new_name='campus_name',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='inst_cnt',
            new_name='institue_count',
        ),
    ]
