# Generated by Django 3.1.4 on 2021-10-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0011_auto_20211010_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_final_years', models.IntegerField(default=0)),
                ('total_higher_study_and_pay_crt', models.IntegerField(default=0)),
                ('total_not_intrested_in_placments', models.IntegerField(default=0)),
                ('total_backlogs', models.IntegerField(default=0)),
                ('total_offers', models.IntegerField(default=0)),
                ('total_multiple_offers', models.IntegerField(default=0)),
                ('highest_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest_salary', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RenameField(
            model_name='institue',
            old_name='under_camp',
            new_name='under_campus',
        ),
        migrations.RenameField(
            model_name='postgraduates',
            old_name='under_inst',
            new_name='under_institute',
        ),
        migrations.RenameField(
            model_name='undergraduates',
            old_name='under_inst',
            new_name='under_institute',
        ),
        migrations.RemoveField(
            model_name='institue',
            name='inst',
        ),
        migrations.RemoveField(
            model_name='postgraduates',
            name='id',
        ),
        migrations.RemoveField(
            model_name='postgraduates',
            name='total_no_of_final_year_students',
        ),
        migrations.RemoveField(
            model_name='postgraduates',
            name='total_no_of_students',
        ),
        migrations.RemoveField(
            model_name='postgraduates',
            name='total_no_of_students_opt_higher_study_and_pay_crt',
        ),
        migrations.RemoveField(
            model_name='undergraduates',
            name='id',
        ),
        migrations.RemoveField(
            model_name='undergraduates',
            name='total_no_of_final_year_students',
        ),
        migrations.RemoveField(
            model_name='undergraduates',
            name='total_no_of_students',
        ),
        migrations.RemoveField(
            model_name='undergraduates',
            name='total_no_of_students_opt_higher_study_and_pay_crt',
        ),
        migrations.AddField(
            model_name='institue',
            name='institute_name',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='campus',
            name='campus_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='postgraduates',
            name='graduates_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example.graduates'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='undergraduates',
            name='graduates_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='example.graduates'),
            preserve_default=False,
        ),
    ]
