# Generated by Django 3.2.8 on 2022-01-30 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(default=None, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('can_edit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AccountsCampusLevel',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.campus')),
            ],
            bases=('accounts.accounts',),
        ),
        migrations.CreateModel(
            name='AccountsHead',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('role', models.CharField(default='head', max_length=10)),
            ],
            bases=('accounts.accounts',),
        ),
        migrations.CreateModel(
            name='AccountsInstituteLevel',
            fields=[
                ('accountscampuslevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountscampuslevel')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institute')),
            ],
            bases=('accounts.accountscampuslevel',),
        ),
        migrations.CreateModel(
            name='AccountsGraduationLevel',
            fields=[
                ('accountsinstitutelevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountsinstitutelevel')),
                ('grad', models.CharField(choices=[('pg', 'PG'), ('ug', 'UG')], max_length=4)),
            ],
            bases=('accounts.accountsinstitutelevel',),
        ),
    ]
