# Generated by Django 3.2.8 on 2022-01-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220106_1939'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='can_edit',
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('institute', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.institute')),
            ],
        ),
    ]
