# Generated by Django 3.2.8 on 2022-01-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0002_auto_20220130_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='campus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.campus'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='eid',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='institute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.institute'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='account',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
        migrations.AlterField(
            model_name='admins',
            name='institute',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.institute'),
        ),
    ]
