# Generated by Django 3.2.8 on 2022-01-30 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0003_auto_20220130_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gcgc',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('grad_level', models.CharField(choices=[('pg', 'PG'), ('ug', 'UG'), ('both', 'Both')], max_length=5)),
                ('campus_level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.campus')),
                ('intitutue_level', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.institute')),
            ],
            bases=('accounts.accounts',),
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='ug_pg',
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('grad_level', models.CharField(choices=[('pg', 'PG'), ('ug', 'UG'), ('both', 'Both')], max_length=5)),
                ('campus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.campus')),
                ('intitutue', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.institute')),
            ],
            bases=('accounts.accounts',),
        ),
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
