# Generated by Django 3.2.8 on 2022-01-30 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0004_auto_20220130_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('campus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.campus')),
            ],
            bases=('accounts.accounts',),
        ),
    ]
