# Generated by Django 3.2.8 on 2022-01-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_head'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='campus',
            new_name='campus_level',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='intitutue',
            new_name='intitutue_level',
        ),
    ]
