# Generated by Django 3.2.8 on 2022-01-30 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0006_auto_20220130_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcgc',
            options={'ordering': ['-campus_level']},
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'ordering': ['-campus_level']},
        ),
        migrations.AlterField(
            model_name='head',
            name='campus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.campus'),
        ),
    ]
