# Generated by Django 3.2.8 on 2022-01-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0007_auto_20220130_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsCampusLevel',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.campus')),
            ],
            bases=('accounts.accounts',),
        ),
        migrations.RemoveField(
            model_name='general',
            name='accounts_ptr',
        ),
        migrations.RemoveField(
            model_name='general',
            name='campus_level',
        ),
        migrations.RemoveField(
            model_name='general',
            name='intitutue_level',
        ),
        migrations.RemoveField(
            model_name='head',
            name='accounts_ptr',
        ),
        migrations.RemoveField(
            model_name='head',
            name='campus',
        ),
        migrations.AddField(
            model_name='accounts',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountsInstituteLevel',
            fields=[
                ('accountscampuslevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountscampuslevel')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.institute')),
            ],
            bases=('accounts.accountscampuslevel',),
        ),
        migrations.DeleteModel(
            name='Gcgc',
        ),
        migrations.DeleteModel(
            name='General',
        ),
        migrations.DeleteModel(
            name='Head',
        ),
        migrations.CreateModel(
            name='AccountsGraduationLevel',
            fields=[
                ('accountsinstitutelevel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accountsinstitutelevel')),
                ('grad', models.CharField(choices=[('pg', 'PG'), ('ug', 'UG')], max_length=4)),
            ],
            bases=('accounts.accountsinstitutelevel',),
        ),
    ]
