# Generated by Django 3.2.8 on 2022-01-30 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220130_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsHead',
            fields=[
                ('accounts_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.accounts')),
                ('role', models.CharField(default='', max_length=10)),
            ],
            bases=('accounts.accounts',),
        ),
    ]
