# Generated by Django 3.2.8 on 2022-01-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountshead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountshead',
            name='role',
            field=models.CharField(default='head', max_length=10),
        ),
    ]
