# Generated by Django 3.2.8 on 2022-01-31 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0010_alter_accountshead_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorInstitutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='accountsgraduationlevel',
            name='accountsinstitutelevel_ptr',
        ),
        migrations.RemoveField(
            model_name='accountshead',
            name='accounts_ptr',
        ),
        migrations.RemoveField(
            model_name='accountsinstitutelevel',
            name='accountscampuslevel_ptr',
        ),
        migrations.RemoveField(
            model_name='accountsinstitutelevel',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='can_edit',
        ),
        migrations.AddField(
            model_name='accounts',
            name='access',
            field=models.CharField(choices=[('view', 'VIEW'), ('edit', 'EDIT')], default=None, max_length=4),
        ),
        migrations.AddField(
            model_name='accounts',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='accounts',
            name='university',
            field=models.CharField(choices=[('university', 'UNIVERSITY'), ('visakhapatnam', 'VISAKHAPATNAM'), ('hyderabad', 'HYDERABAD'), ('bengaluru', 'BENGALURU')], default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='AccountsCampusLevel',
        ),
        migrations.DeleteModel(
            name='AccountsGraduationLevel',
        ),
        migrations.DeleteModel(
            name='AccountsHead',
        ),
        migrations.DeleteModel(
            name='AccountsInstituteLevel',
        ),
        migrations.AddField(
            model_name='editorinstitutes',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='editorinstitutes',
            name='institute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.institute'),
        ),
    ]
