# Generated by Django 3.2.8 on 2022-01-31 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220201_0009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='accounts',
            name='access',
            field=models.CharField(choices=[('view', 'VIEW'), ('edit', 'EDIT')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='designation',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='university',
            field=models.CharField(choices=[('university', 'UNIVERSITY'), ('visakhapatnam', 'VISAKHAPATNAM'), ('hyderabad', 'HYDERABAD'), ('bengaluru', 'BENGALURU')], default=None, max_length=15, null=True),
        ),
    ]
