# Generated by Django 3.2.8 on 2022-01-31 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0012_auto_20220201_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorinstitutes',
            name='can_edit_all_campus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='editorinstitutes',
            name='can_edit_all_university',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='access',
            field=models.CharField(choices=[('', 'None'), ('view', 'VIEW'), ('edit', 'EDIT')], default=None, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='designation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='university',
            field=models.CharField(choices=[('', 'None'), ('university', 'UNIVERSITY'), ('visakhapatnam', 'VISAKHAPATNAM'), ('hyderabad', 'HYDERABAD'), ('bengaluru', 'BENGALURU')], default=None, max_length=15, null=True),
        ),
        migrations.RemoveField(
            model_name='editorinstitutes',
            name='institute',
        ),
        migrations.AddField(
            model_name='editorinstitutes',
            name='institute',
            field=models.ManyToManyField(to='organization.Institute'),
        ),
    ]
