# Generated by Django 3.2.8 on 2022-01-31 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
        ('accounts', '0013_auto_20220201_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorinstitutes',
            name='institute',
        ),
        migrations.AddField(
            model_name='editorinstitutes',
            name='institute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='organization.institute'),
        ),
    ]
