# Generated by Django 3.2.8 on 2022-01-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20220201_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorinstitutes',
            name='can_edit_all_campus',
        ),
        migrations.RemoveField(
            model_name='editorinstitutes',
            name='can_edit_all_university',
        ),
    ]
