# Generated by Django 3.2.8 on 2022-01-31 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220201_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='university',
            field=models.CharField(choices=[('', 'None'), ('univ', 'UNIVERSITY'), ('vskp', 'VISAKHAPATNAM'), ('hyd', 'HYDERABAD'), ('blr', 'BENGALURU')], default=None, max_length=15, null=True),
        ),
    ]
