# Generated by Django 3.2.8 on 2022-01-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_accounts_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='access',
            field=models.CharField(choices=[('', 'None'), ('view', 'VIEW'), ('edit_all', 'EDIT ALL'), ('edit_some', 'EDIT SOME')], default=None, max_length=10, null=True),
        ),
    ]
