# Generated by Django 3.2.8 on 2021-10-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gim_BBA_BCOM',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.company')),
                ('BBA', models.IntegerField(default=0)),
                ('BCOM', models.IntegerField(default=0)),
                ('BBA_Logistics', models.IntegerField(default=0)),
                ('BBA_Business_Analytics', models.IntegerField(default=0)),
            ],
            bases=('company.company',),
        ),
        migrations.CreateModel(
            name='Gim_MBA',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.company')),
                ('MBA_Finance', models.IntegerField(default=0)),
                ('MBA_HR', models.IntegerField(default=0)),
                ('MBA_Marketing', models.IntegerField(default=0)),
                ('MBA_IB', models.IntegerField(default=0)),
                ('MBA', models.IntegerField(default=0)),
            ],
            bases=('company.company',),
        ),
    ]
