# Generated by Django 3.2.8 on 2021-12-31 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20211028_1226'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCousesPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.IntegerField(default=-1)),
                ('company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=10)),
                ('is_ug', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.campus')),
                ('institute', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.institute')),
            ],
        ),
        migrations.RemoveField(
            model_name='gim_mba',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='gis',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='git',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='company_ptr',
        ),
        migrations.DeleteModel(
            name='Gim_BBA_BCOM',
        ),
        migrations.DeleteModel(
            name='Gim_MBA',
        ),
        migrations.DeleteModel(
            name='Gis',
        ),
        migrations.DeleteModel(
            name='Git',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
        migrations.AddField(
            model_name='companycousesplaced',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.courses'),
        ),
        migrations.AddField(
            model_name='company',
            name='courses',
            field=models.ManyToManyField(through='company.CompanyCousesPlaced', to='company.Courses'),
        ),
    ]
