# Generated by Django 3.2.8 on 2021-12-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gim_mba',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='gis_pg',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='gis_ug',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='git_pg',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='git_ug',
            name='company_ptr',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='company_ptr',
        ),
        migrations.DeleteModel(name='Gim_BBA_BCOM', ),
        migrations.DeleteModel(name='Gim_MBA', ),
        migrations.DeleteModel(name='Gis_pg', ),
        migrations.DeleteModel(name='Gis_ug', ),
        migrations.DeleteModel(name='Git_pg', ),
        migrations.DeleteModel(name='Git_ug', ),
        migrations.DeleteModel(name='Pharmacy', ),
    ]
