# Generated by Django 3.2.8 on 2021-12-12 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20211028_1226'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='institue',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='students.institute'),
        ),
    ]
