# Generated by Django 3.2.8 on 2021-12-12 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20211028_1226'),
        ('company', '0003_alter_company_institue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='institue',
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='', max_length=30, unique=True)),
                ('is_ug', models.BooleanField(default=True)),
                ('course_placed', models.IntegerField(default=-1)),
                ('institue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.institute')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='courses',
            field=models.ManyToManyField(to='company.Courses'),
        ),
    ]
