# Generated by Django 3.2.8 on 2021-12-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20211212_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='courses',
        ),
        migrations.CreateModel(
            name='CompanyCousesPlaced',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_count', models.IntegerField(default=-1)),
                ('company_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('courses_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.courses')),
            ],
        ),
    ]
