# Generated by Django 3.2.8 on 2021-12-25 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_courses_is_ug'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='courses',
            field=models.ManyToManyField(to='company.Courses'),
        ),
    ]
