# Generated by Django 3.2.8 on 2021-12-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20211212_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_placed',
        ),
    ]
