# Generated by Django 3.2.8 on 2021-12-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20211225_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companycousesplaced',
            old_name='courses',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='companycousesplaced',
            old_name='placed',
            new_name='selected',
        ),
    ]
