# Generated by Django 3.2.8 on 2021-12-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_courses_course_placed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycousesplaced',
            name='courses_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.courses', unique=True),
        ),
    ]
