# Generated by Django 3.2.8 on 2021-12-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_companycousesplaced_courses_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycousesplaced',
            name='courses_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.courses'),
        ),
    ]
