# Generated by Django 3.2.8 on 2021-12-12 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_companycousesplaced_courses_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companycousesplaced',
            options={'ordering': ['company_id']},
        ),
    ]
