# Generated by Django 3.2.8 on 2022-01-06 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name',
                 models.CharField(default='', max_length=30, unique=True)),
                ('inst_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10)),
                ('under_campus',
                 models.ForeignKey(null=True,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='organization.campus')),
            ],
        ),
    ]
