# Generated by Django 3.2.8 on 2022-07-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='institute',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='is_ug',
        ),
    ]
