# Generated by Django 3.2.8 on 2022-07-08 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20220708_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=36)),
                ('under_campus', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.campus')),
                ('under_institute', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.institute')),
            ],
        ),
    ]
