# Generated by Django 3.2.8 on 2022-01-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('name',
                 models.CharField(default='', max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='institute',
            name='under_campus',
            field=models.ForeignKey(
                default='',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='organization.campus'),
        ),
        migrations.AddField(
            model_name='institute',
            name='stream',
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='organization.stream'),
        ),
    ]
