# Generated by Django 3.2.8 on 2022-01-30 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20220106_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='institute',
            name='under_campus',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.campus'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(default=None, max_length=20, unique=True),
        ),
    ]
