# Generated by Django 3.2.8 on 2022-07-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='is_ug',
            field=models.BooleanField(default=False),
        ),
    ]
