# Generated by Django 3.2.8 on 2022-07-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_programs_is_ug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='programs',
            unique_together={('under_campus', 'under_institute', 'name', 'is_ug')},
        ),
    ]
