# Generated by Django 3.2.8 on 2022-07-08 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_alter_courses_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='under_course',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.courses'),
        ),
    ]
