# Generated by Django 3.2.8 on 2021-10-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_name', models.CharField(default='', max_length=30)),
                ('institue_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_final_years', models.IntegerField(default=0)),
                ('total_higher_study_and_pay_crt', models.IntegerField(default=0)),
                ('total_not_intrested_in_placments', models.IntegerField(default=0)),
                ('total_backlogs', models.IntegerField(default=0)),
                ('total_offers', models.IntegerField(default=0)),
                ('total_multiple_offers', models.IntegerField(default=0)),
                ('highest_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lowest_salary', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Institue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(default='', max_length=10)),
                ('under_campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_api.campus')),
            ],
        ),
        migrations.CreateModel(
            name='UnderGraduates',
            fields=[
                ('graduates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_api.graduates')),
                ('under_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_api.institue')),
            ],
            bases=('student_api.graduates',),
        ),
        migrations.CreateModel(
            name='PostGraduates',
            fields=[
                ('graduates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_api.graduates')),
                ('under_institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_api.institue')),
            ],
            bases=('student_api.graduates',),
        ),
    ]
