# Generated by Django 3.2.8 on 2021-10-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduates',
            name='average_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='highest_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='lowest_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='postgraduates',
            name='under_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_api.institue'),
        ),
        migrations.AlterField(
            model_name='undergraduates',
            name='under_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student_api.institue'),
        ),
    ]
