# Generated by Django 3.2.8 on 2021-10-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_api', '0002_auto_20211012_2025'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institue',
            new_name='Institute',
        ),
        migrations.RenameField(
            model_name='campus',
            old_name='institue_count',
            new_name='institute_count',
        ),
    ]
