# Generated by Django 3.2.8 on 2022-02-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(name='ExcelData', ),
        migrations.AlterUniqueTogether(
            name='graduates',
            unique_together={('under_campus', 'under_institute', 'is_ug')},
        ),
    ]
