# Generated by Django 3.2.8 on 2022-02-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduates',
            options={'ordering': ['-under_campus']},
        ),
        migrations.AlterUniqueTogether(
            name='graduates',
            unique_together={('under_campus', 'under_institute', 'is_ug')},
        ),
    ]
