# Generated by Django 3.2.8 on 2021-10-15 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_campus_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='count_inst',
            new_name='ints_count',
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=10, unique=True)),
                ('under_campus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='students.campus')),
            ],
        ),
    ]
