# Generated by Django 3.2.8 on 2022-02-06 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220204_0058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduates',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='graduates',
            unique_together=set(),
        ),
    ]
