# Generated by Django 3.2.8 on 2022-02-11 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220211_0142'),
        ('students', '0003_auto_20220206_1207'),
    ]

    operations = []
