# Generated by Django 3.2.8 on 2021-10-15 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_ints_count_campus_inst_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
