# Generated by Django 3.2.8 on 2022-07-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_programs_under_course'),
        ('students', '0005_alter_graduates_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatesWithPrograms',
            fields=[
                ('graduates_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='students.graduates')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.programs')),
            ],
            bases=('students.graduates',),
        ),
    ]
