# Generated by Django 3.2.8 on 2022-07-09 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_programs_under_course'),
        ('students', '0005_alter_graduates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduates',
            options={'ordering': ('passing_year', '-is_ug', 'under_campus', 'under_institute')},
        ),
        migrations.AddField(
            model_name='graduates',
            name='passing_year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2022', max_length=4),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='is_ug',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='graduates',
            unique_together={('under_campus', 'under_institute', 'is_ug', 'passing_year')},
        ),
        migrations.CreateModel(
            name='GraduatesWithPrograms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.programs')),
            ],
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='created',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='updated',
        ),
    ]
