# Generated by Django 3.2.8 on 2022-07-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_programs_under_course'),
        ('students', '0006_auto_20220709_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduateswithprograms',
            options={
                'ordering':
                ('passing_year', '-is_ug', 'under_campus', 'under_institute')
            },
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='average_salary',
            field=models.DecimalField(decimal_places=2,
                                      default=0.0,
                                      max_digits=5),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='highest_salary',
            field=models.DecimalField(decimal_places=2,
                                      default=0.0,
                                      max_digits=5),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='is_ug',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='lowest_salary',
            field=models.DecimalField(decimal_places=2,
                                      default=0.0,
                                      max_digits=5),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='passing_year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'),
                                            ('2023', '2023'), ('2024', '2024'),
                                            ('2025', '2025')],
                                   default='2022',
                                   max_length=4),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_backlogs_opted_for_higherstudies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_backlogs_opted_for_other_career_options',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_backlogs_opted_for_placements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_final_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_higher_study_and_pay_crt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_multiple_offers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_not_intrested_in_placments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_offers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_opted_for_higher_studies_only',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='total_students',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='under_campus',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='organization.campus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduateswithprograms',
            name='under_institute',
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to='organization.institute'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='graduateswithprograms',
            unique_together={('under_campus', 'under_institute', 'is_ug',
                              'passing_year')},
        ),
    ]
