# Generated by Django 3.2.8 on 2022-07-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_graduateswithprograms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduates',
            name='created',
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='updated',
        ),
        migrations.AddField(
            model_name='graduates',
            name='passing_year',
            field=models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2022', max_length=4),
        ),
    ]
