# Generated by Django 3.2.8 on 2022-07-11 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_programs_under_course'),
        ('students', '0007_auto_20220709_1358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduateswithprograms',
            unique_together={('under_campus', 'under_institute', 'is_ug',
                              'passing_year', 'program')},
        ),
    ]
