# Generated by Django 3.2.8 on 2021-10-28 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20211015_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduates',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('total_students', models.IntegerField(default=0)),
                ('total_final_years', models.IntegerField(default=0)),
                ('total_higher_study_and_pay_crt',
                 models.IntegerField(default=0)),
                ('total_not_intrested_in_placments',
                 models.IntegerField(default=0)),
                ('total_backlogs', models.IntegerField(default=0)),
                ('total_offers', models.IntegerField(default=0)),
                ('total_multiple_offers', models.IntegerField(default=0)),
                ('highest_salary',
                 models.DecimalField(decimal_places=2,
                                     default=0.0,
                                     max_digits=5)),
                ('average_salary',
                 models.DecimalField(decimal_places=2,
                                     default=0.0,
                                     max_digits=5)),
                ('lowest_salary',
                 models.DecimalField(decimal_places=2,
                                     default=0.0,
                                     max_digits=5)),
                ('is_ug', models.BooleanField(default=True)),
                ('under_campus',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='students.campus')),
                ('under_institute',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='students.institute')),
            ],
        ),
        migrations.RemoveField(
            model_name='undergraduates',
            name='under_campus',
        ),
        migrations.RemoveField(
            model_name='undergraduates',
            name='under_institute',
        ),
        migrations.DeleteModel(name='PostGraduates', ),
        migrations.DeleteModel(name='UnderGraduates', ),
    ]
