# Generated by Django 3.2.8 on 2022-01-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courses'),
        ('students', '0009_auto_20220106_1336'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduates',
            unique_together={('under_campus', 'under_institute')},
        ),
    ]
