# Generated by Django 3.2.8 on 2022-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_graduateswithprograms_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companies', models.IntegerField(default=0)),
                ('students_placed', models.IntegerField(default=0)),
                ('Highest_package', models.IntegerField(default=0)),
                ('off_placements', models.IntegerField(default=0)),
                ('passing_year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025')], default='2022', max_length=4)),
            ],
        ),
    ]
