# Generated by Django 3.2.8 on 2022-01-06 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_alter_graduates_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graduates',
            unique_together=set(),
        ),
    ]
