# Generated by Django 3.2.8 on 2022-01-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_exceldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduates',
            name='total_opted_for_higher_studies',
            field=models.IntegerField(default=0),
        ),
    ]
