# Generated by Django 3.2.8 on 2022-01-30 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_graduates_total_opted_for_higher_studies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduates',
            old_name='total_opted_for_higher_studies',
            new_name='total_opted_for_higher_studies_only',
        ),
    ]
