# Generated by Django 3.2.8 on 2022-02-01 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_auto_20220130_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('eid',
                 models.CharField(default=None, max_length=10, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('designation', models.CharField(default='', max_length=100)),
                ('university',
                 models.CharField(choices=[('univ', 'UNIVERSITY'),
                                           ('vskp', 'VISAKHAPATNAM'),
                                           ('hyd', 'HYDERABAD'),
                                           ('blr', 'BENGALURU')],
                                  default='vskp',
                                  max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('access',
                 models.CharField(choices=[('view', 'VIEW'),
                                           ('edit_all', 'EDIT ALL'),
                                           ('edit_some', 'EDIT SOME')],
                                  default='view',
                                  max_length=10)),
            ],
            options={
                'ordering': ('id', ),
            },
        ),
        migrations.CreateModel(
            name='EditorInstitutes',
            fields=[
                ('id',
                 models.BigAutoField(auto_created=True,
                                     primary_key=True,
                                     serialize=False,
                                     verbose_name='ID')),
                ('account',
                 models.ForeignKey(default=None,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='account.accounts')),
                ('institute',
                 models.ForeignKey(default=None,
                                   on_delete=django.db.models.deletion.CASCADE,
                                   to='organization.institute')),
            ],
        ),
    ]
